#! /usr/bin/env python
import os
import sys
import struct
import time

# usage:
#i2csetter_fromtxt.py textfile.txt
#This script is designed to program a text file
#generated by i2cdump 0x50 > testfile.txt.
#Note: it programs the whole file, not just the
#last 128 bytes.

infile = sys.argv[1]
addr = 0x50 #int(sys.argv[2],16)
page = 0 #int(sys.argv[3],16)

offset = 0


print 'Writing from file', infile

with open(infile, 'r') as fh:
    string = fh.read()

lines = string.split('\n')

d = []
for x in lines[1:]:
    print x.split()[1:17]
    d += x.split()[1:17]

print d, len(d)

for vn, v in enumerate(d):
    #print 'Writing val %x to location %x'%(v,vn)
    print 'calling i2cset -y 1 0x%.2x 0x%.2x 0x%.2x'%(addr, vn+offset,int(v,16))
    os.system('i2cset -y 1 0x%.2x 0x%.2x 0x%.2x'%(addr, vn+offset,int(v,16)))
    time.sleep(0.05)
